name: CI

on:
  push:
    branches: [ "main", "121-continous-deployment" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: car-racing-tournament-api
    - name: Build
      run: dotnet build --no-restore
      working-directory: car-racing-tournament-api
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: car-racing-tournament-api

  backend-migrate:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: backend-check
    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Migrate database
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: dotnet ef database update --no-build --connection "${{ env.CONNECTION_STRING }}" 
        working-directory: car-racing-tournament-api

  backend-deploy-web:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: backend-check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Publish application
      run: dotnet publish -c Release -o publish --no-restore
      working-directory: car-racing-tournament-api
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'car-racing-tournament-api'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_API }}
        package: './car-racing-tournament-api/publish'

  webapp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: car-racing-tournament-web/package-lock.json
    - run: npm ci
      working-directory: car-racing-tournament-web
    - run: npm run build --if-present
      working-directory: car-racing-tournament-web
    #- run: npm test
    #  working-directory: car-racing-tournament-web
